---
include:
  - board: nice_nano_v2
    shield: blocky_dongle
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: blocky_right
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset