---
include:
  - board: nice_nano_v2
    shield: sweeple_left
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: sweeple_right
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: sweeple_dongle
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset