---
include:
  - board: nice_nano_v2
    shield: corne_tp_left
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: corne_tp_right
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset