# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  - board: nice_nano_v2
    shield: corne_tp_left
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: corne_tp_right
    snippet: zmk-usb-logging

  # Alternative PINs firmware
  # This builds an additional firmware for the right half that overrides the
  # pins configured in `corne_tp_right.overlay` and creates a firmware that
  # uses the high frequency pins D1 for SCL and D2 for SDA.
  #

  # Settings Reset firmware
  # This will build a firmware that can wipe all settings from your
  # controller. It's useful when you have bluetooth issues or when your split
  # keyboard halfs are not pairing.
  #
  # More info:
  # https://zmk.dev/docs/troubleshooting#split-keyboard-halves-unable-to-pair
  - board: nice_nano_v2
    shield: settings_reset