manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: madswolf
      url-base: https://github.com/madswolf
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # Module for PS/2 mouse & TP driver
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: madswolf
      revision: main

  self:
    path: config
